
name: Expo CI CD

on:
  push :
    branches :
      - preview
jobs:
  Build-for-android:
    runs-on: ubuntu-latest
    steps:
    - name: Check for EXPO_TOKEN
      run: |
        echo  ${{ github.repository.name }}
        if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
          echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
          exit 1
        fi
    
    # - name: Checkout repository
    #   uses: actions/checkout@v4
    
    # - name: Setup Node
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: 18.x

    # - name: Setup JDK
    #   uses: actions/setup-java@v1
    #   with:
    #     java-version: 17

    # - name: Setup EAS
    #   uses: expo/expo-github-action@v8
    #   with:
    #     eas-version: "12.4.1"
    #     token: ${{ secrets.EXPO_TOKEN }}

    # - name: Install dependencies
    #   run: npm install

    # - name: Build Android APK Bundle
    #   run: npm run build:preview:local

    # - name: Upload APK
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: build-apk
    #     path: /home/runner/work/${{ github.repository.name }}/${{ github.repository.name }}/*.apk